name: CI

on:
  push:
    paths:
      - 'src/main'

jobs:
  generateFilter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.email "<>"
        git config user.name "Actions CI Bot"

    - name: Make
      run: |
        make

    - name: Push changes
      run: |
        LAST_MSG="$(git log --oneline -1 | cut -d' ' -f2-)"
        git add out/list.txt
        git commit -m "release filterlist after: \"${LAST_MSG}\""
        git push origin
